language: go
sudo: false
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

git:
  depth: 10

go_import_path: github.com/night-codes/runner

before_install:
  - sudo add-apt-repository ppa:webkit-team/ppa
  - sudo apt-get update
  - sudo apt-get install -y build-essential libgtk-3-dev libgtk2.0-dev libwebkit2gtk-4.0-dev

install:
  - go get golang.org/x/tools/cmd/cover
  - go list -f '{{range .Imports}}{{.}} {{end}}' ./... | xargs go get -v

script:
  - go vet
  - go test -v ./... -cover
  - go build -o build
  - ./build example
